# Generated by Django 5.1.3 on 2024-11-16 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Group Name")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Group's Description"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                ("event_date", models.DateField(verbose_name="Event's Date")),
                (
                    "budget_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Budget Limit",
                    ),
                ),
                (
                    "is_matched",
                    models.BooleanField(
                        default=False, verbose_name="Have the matches been completed?"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Group's Creator",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "db_table": "group",
                "ordering": ("event_date", "name"),
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wishlist",
                    models.TextField(
                        blank=True, null=True, verbose_name="Member's whishlist"
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Joined Datetime"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        help_text="Group that this Member is part of",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_members",
                        to="santa.group",
                        verbose_name="Groups",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="santa_for",
                        to="santa.groupmember",
                        verbose_name="Gift Recipient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Group Member",
                "verbose_name_plural": "Group Members",
                "db_table": "group_member",
                "ordering": ("joined_at",),
                "unique_together": {("user", "group")},
            },
        ),
        migrations.AddField(
            model_name="group",
            name="members",
            field=models.ManyToManyField(
                related_name="created_groups",
                through="santa.GroupMember",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Group's Members",
            ),
        ),
    ]
